version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  ranglin:
    build: .
    volumes:
      - .:/home/app_user/ranglin
      - /home/app_user/ranglin/node_modules
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
